### ISSUE TITLE
Stack-ify!

### ISSUE THREAD

**Issue by tebello-thejane** [winterland1989/hterm#3]
It might be nice to have this project be buildable with `stack` (especially since it is an independent application rather than a simple Haskell library). That way the instructions can simply be
1. Install stack
2. Clone
3. `stack install`
without having to worry about install `GHC` and `cabal install` first.

I will create a merge request shortly, if there are no objections.

**Comment by winterland1989** [comment]
I'm OK with adding stack support,  as long as cabal user can still build them without stack.
Do i have to limit the version range in cabal? I really have no idea how to figure out the right version range on hackage.

**Comment by tebello-thejane** [comment]
`stack` lives very well besides `Cabal-install`, and indeed it relies upon the `cabal` library to do its job. 

You do not need to set ranges to have it work, although you might want to consider doing so anyway. 

I will clone the repo shortly and see if I uncover any difficulties.

**Comment by winterland1989** [comment]
Keep this issue open to remind me to add version range in cabal, thanks for adding stack support!

**Comment by winterland1989** [comment]
Version range added : )
