### ISSUE TITLE
vim输不了中文

### ISSUE THREAD

**Issue by dengyaolong** [winterland1989/hterm#5]
正常情况下命令行都输不了中文，我想做一些有中文的文本处理都不行。只能复制黏贴?
vim里面连黏贴都不行哦。
还有怎么容易closed啊。难道是我信号太差了。

**Comment by winterland1989** [comment]
这个模拟的终端基本原理是监听keydown事件，而不是通过input输入框，这导致系统输入法无法调出，如果希望修复这个bug可能会改掉整个前端的构架，我会试试看，你有想法的话也可以帮忙看下static下面的js文件，不过这个bug恐怕很难搞定：）

至于closed的问题，可能是某些转义之后控制字符我在js里面没处理，你可否把浏览器网络的消息和js的输出发上来？

**Comment by winterland1989** [comment]
没有后续反馈，关闭了哈
